"""
Goal management toolkit for interactive/dynamic goal management during agent sessions.

Provides tools for creating, managing, and tracking goals with hierarchical
structure, priority levels, and status lifecycle. Goals are stored in session
state and persist throughout the agent conversation.
"""

from collections.abc import Callable
from datetime import datetime
from typing import Any, cast

from agno.run import RunContext
from agno.tools import Toolkit

from blockether_foundation.models import (
    Goal,
    GoalPriority,
    GoalStatus,
)

type GoalsDict = dict[str, Goal]


def _ensure_session_state(run_context: RunContext) -> tuple[GoalsDict, str | None]:
    """Ensure session state is initialized and return goals dict and current goal ID."""
    if run_context.session_state is None:
        run_context.session_state = {"goals": {}, "current_goal_id": None}

    if "goals" not in run_context.session_state:
        run_context.session_state["goals"] = {}

    if "current_goal_id" not in run_context.session_state:
        run_context.session_state["current_goal_id"] = None

    goals_data = run_context.session_state.get("goals", {})
    # Cast to GoalsDict - at runtime we trust that the session_state contains the correct types
    goals: GoalsDict = cast(GoalsDict, goals_data) if isinstance(goals_data, dict) else {}

    current_goal_id_val = run_context.session_state.get("current_goal_id")
    current_goal_id: str | None = (
        current_goal_id_val if isinstance(current_goal_id_val, str) else None
    )

    return goals, current_goal_id


class GoalToolkit(Toolkit):
    """Toolkit for goal management with hierarchical structure and lifecycle tracking."""

    def __init__(self, **kwargs: Any):
        tools: list[Callable[..., str]] = [
            self.create_goal,
            self.list_goals,
            self.finish_goal,
            self.skip_goal,
            self.refine_goal,
            self.jump_to_goal,
            self.set_goal_priority,
            self.get_current_goal,
        ]

        instructions = """
# Goal Management Toolkit

## ROLE
You are an agent with access to hierarchical goal management for tracking and organizing
complex multi-step tasks throughout a session. Goals persist in session state and help
maintain focus, progress tracking, and task prioritization.

## ACTION
Use these tools to manage goals throughout the agent session:
- create_goal: Create new goals with priority, importance, and subgoals
- list_goals: View all goals with status and details
- finish_goal: Mark goals as completed
- skip_goal: Skip goals without finishing
- refine_goal: Update goal attributes
- jump_to_goal: Switch active goal
- set_goal_priority: Change goal priority
- get_current_goal: View current goal details

## STEPS - How to Use These Tools

### Step 1: Create Goals When Needed
When given a complex or multi-step task, break it down into goals:
```
create_goal(
    title="Implement user authentication",
    description="Add JWT-based authentication with login/logout endpoints",
    priority="P1",  # P0 (critical), P1 (high), P2 (medium), P3 (low)
    importance=0.9,  # 0.0-1.0 scale
    summary="Optional brief summary"
)
```

### Step 2: Track Progress with list_goals
Regularly check goal status to see what's pending and what's complete:
```
list_goals(include_finished=True, include_subgoals=False)
```

### Step 3: Update Goals as You Work
- Mark goals complete: finish_goal(goal_id="goal_2_20250104123457", summary="What was accomplished")
- Skip blocked goals: skip_goal(goal_id="goal_3_20250104123458", reason="Why skipping")
- Refine as needed: refine_goal(goal_id="goal_1_20250104123456", new_title="Updated title")
- Switch focus: jump_to_goal(goal_id="goal_4_20250104123459")

### Step 4: Maintain Current Goal Context
Use get_current_goal to see what you should be working on:
```
get_current_goal()  # Returns active goal details
```

## CONTEXT

**Goal Structure:**
- Each goal has: ID (auto-generated by toolkit), title, description, priority, importance (0.0-1.0), status
- Goals can have parent/child relationships (hierarchical)
- Only ONE goal is "current" (in_progress) at a time
- Goals auto-advance to highest priority pending goal when current is finished/skipped

**ID Generation:**
- IDs are automatically generated by the toolkit using: goal_{N}_{timestamp}
- N = current number of goals + 1 (e.g., first goal is goal_1_...)
- timestamp = YYYYMMDDHHMMSS format (e.g., 20250104123456)
- Never manually construct IDs - always copy from list_goals() output

**Priority Levels:**
- P0 (HIGHEST): Critical, blocking, or time-sensitive tasks
- P1 (HIGH): Important tasks with significant impact
- P2 (MEDIUM): Standard priority tasks (default)
- P3 (LOW): Nice-to-have or low-impact tasks

**Status Lifecycle:**
- pending: Created but not yet started
- in_progress: Currently active goal (only one at a time)
- completed: Successfully finished
- skipped: Intentionally bypassed (with reason)
- refined: Modified after creation

**Session Persistence:**
- Goals stored in run_context.session_state
- Survive throughout the entire conversation
- Lost when session ends (not persisted to disk)

## EXAMPLES

**Example 1 - Creating Initial Goals:**
```
# User asks: "Help me add authentication and fix the payment bug"

1. create_goal(title="Add authentication", description="...", priority="P1")
   → Returns: "Created goal 'Add authentication' (ID: goal_1_20250104123456)"

2. create_goal(title="Fix payment bug", description="...", priority="P0")
   → Returns: "Created goal 'Fix payment bug' (ID: goal_2_20250104123457)"

3. list_goals() to confirm structure and see goal IDs
```

**Example 2 - Working Through Goals:**
```
# After creating goals, work through them

1. get_current_goal() → Shows: "Fix payment bug" (P0, ID: goal_2_20250104123457)
2. Complete the fix
3. finish_goal(goal_id="goal_2_20250104123457", summary="Added mutex lock to payment processing")
   → System auto-switches to next highest priority goal (Add authentication)
```

**Example 3 - Handling Blocked Work:**
```
# When current goal is blocked

1. list_goals() → Find the current goal ID (e.g., goal_3_20250104123458)
   → Shows: "3. [IN_PROGRESS] Add email notifications (ID: goal_3_20250104123458) ← CURRENT"
2. get_current_goal() → "Add email notifications"
3. Discover missing email service configuration
4. skip_goal(goal_id="goal_3_20250104123458", reason="Blocked: email service credentials not configured")
   → System auto-switches to next pending goal
5. Or use jump_to_goal(goal_id="goal_1_20250104123456") to switch to a specific goal
```

**Example 3b - Handling Positional References:**
```
# User says: "Refine the first goal and make it priority higher"

1. list_goals() → Shows:
   "1. [PENDING] Implement caching (ID: goal_1_20250104123456)"
   "2. [PENDING] Add logging (ID: goal_2_20250104123457)"
   "3. [IN_PROGRESS] Fix bug (ID: goal_3_20250104123458) ← CURRENT"

2. Resolve "first goal" → goal_1_20250104123456 (from line 1)
3. refine_goal(goal_id="goal_1_20250104123456", new_priority="P1")
```

**Example 4 - Refining Goals:**
```
# When a goal needs to be more specific

1. list_goals() → Find the goal to refine (e.g., goal_5_20250104123459)
2. refine_goal(
       goal_id="goal_5_20250104123459",
       new_title="Implement OAuth2 with Google provider",
       new_description="Add Google OAuth2 login using authlib package",
       new_priority="P1"
   )
   → Status changes to "refined", goal remains current
```

**Example 5 - Hierarchical Goals:**
```
# Creating parent and sub-goals

1. create_goal(title="Build dashboard", description="...", priority="P1", parent_goal_id=None)
   → Returns: "Created goal 'Build dashboard' (ID: goal_1_20250104123456)"

2. create_goal(title="Design layout", description="...", parent_goal_id="goal_1_20250104123456")
   → Returns: "Created goal 'Design layout' (ID: goal_2_20250104123457)"

3. create_goal(title="Implement widgets", description="...", parent_goal_id="goal_1_20250104123456")
   → Returns: "Created goal 'Implement widgets' (ID: goal_3_20250104123458)"

4. list_goals(include_subgoals=True) → Shows all goals with hierarchy
```

## FORMAT

**list_goals output:**
```
Goals:

1. [PENDING] Add authentication (ID: goal_1_20250104123456)
  Priority: HIGH | Importance: 0.9
  Summary: Add JWT-based auth

2. [IN_PROGRESS] Fix payment bug (ID: goal_2_20250104123457) ← CURRENT
  Priority: HIGHEST | Importance: 1.0
  Description: Race condition in refund processing...
```

**get_current_goal output:**
```
Current goal: Fix payment race condition
ID: goal_2_20250104123457
Priority: HIGHEST
Importance: 1.0
Status: in_progress

Description:
The refund processing has a race condition when multiple requests...

Subgoals (2):
  1. Add mutex lock [pending]
  2. Add unit tests [pending]
```

**create_goal output:**
```
Created goal 'Add authentication' (ID: goal_1_20250104123456)
  Priority: P1
  Importance: 0.9
  Status: pending
```

## IMPORTANT NOTES

1. **ID Generation:** The toolkit generates goal IDs automatically using format: goal_{N}_{timestamp}
   where N = current number of goals + 1, timestamp = YYYYMMDDHHMMSS (e.g., goal_3_20250104123456)
2. **First Goal Created = Current:** If no current goal exists, newly created goal becomes current
3. **Auto-Advance:** finish_goal() and skip_goal() automatically switch to next highest priority pending goal
4. **Priority Sorting:** P0 (HIGHEST) > P1 (HIGH) > P2 (MEDIUM) > P3 (LOW), then by importance (higher first)
5. **Copy IDs from list_goals:** Always run list_goals() first and copy the exact goal ID for operations
6. **refine_goal Behavior:** Sets status to "refined" but does NOT auto-advance - goal remains current
7. **Subgoals:** Stored in parent goal's subgoals list but not managed separately - focus on top-level goals
8. **Summary Updates:** finish_goal() accepts optional summary to record what was accomplished
 9. **Parent/Child Relationships:** Subgoals are linked via parent_goal_id, but list_goals shows all goals
10. **Positional References:** Each goal is numbered in list_goals() output (1., 2., 3., etc.) for easy positional reference
   - "First goal" = goal with number 1 in list_goals() output
   - "Second goal" = goal with number 2, etc.
   - When a goal is finished/skipped, remaining goals renumber automatically
   - Always use the actual goal ID (from parentheses) for tool operations, not the positional number
   - Positional references are user-friendly aliases - resolve them to goal IDs before calling tools
  """

        super().__init__(
            name="goal_management",
            tools=tools,
            instructions=instructions,
            add_instructions=True,
            **kwargs,
        )

    def create_goal(
        self,
        run_context: RunContext,
        title: str,
        description: str,
        importance: float = 0.5,
        priority: str = "P2",
        parent_goal_id: str | None = None,
        summary: str | None = None,
    ) -> str:
        """Create a new goal with title, description, importance, priority, and optional subgoals."""
        goals, current_goal_id = _ensure_session_state(run_context)
        assert run_context.session_state is not None

        goal_id = f"goal_{len(goals) + 1}_{datetime.now().strftime('%Y%m%d%H%M%S')}"

        try:
            priority_enum = GoalPriority[priority]
        except KeyError:
            priority_enum = GoalPriority.MEDIUM

        goal = Goal(
            id=goal_id,
            title=title,
            description=description,
            summary=summary,
            priority=priority_enum,
            importance=importance,
            status=GoalStatus.PENDING,
            subgoals=[],
            parent_goal_id=parent_goal_id,
        )

        goals[goal_id] = goal

        if parent_goal_id and parent_goal_id in goals:
            parent_goal = goals[parent_goal_id]
            parent_goal.subgoals.append(goal)

        if not current_goal_id:
            run_context.session_state["current_goal_id"] = goal_id

        return (
            f"Created goal '{title}' (ID: {goal_id})\n"
            f"  Priority: {priority}\n"
            f"  Importance: {importance}\n"
            f"  Status: pending"
        )

    def list_goals(
        self,
        run_context: RunContext,
        include_finished: bool = True,
        include_subgoals: bool = True,
    ) -> str:
        """List all goals with their status, priority, and details."""
        goals, current_goal_id = _ensure_session_state(run_context)

        if not goals:
            return "No goals exist yet. Use create_goal to create your first goal."

        result = ["Goals:", ""]
        visible_count = 0

        for goal_id, goal in goals.items():
            # Skip finished goals if include_finished is False
            if not include_finished and goal.status in (GoalStatus.COMPLETED, GoalStatus.SKIPPED):
                continue
            visible_count += 1
            status_marker = "← CURRENT" if goal_id == current_goal_id else ""
            status_display = f"[{goal.status.value.upper()}]"

            result.append(
                f"{visible_count}. {status_display} {goal.title} (ID: {goal_id}) {status_marker}"
            )
            result.append(f"  Priority: {goal.priority.name} | Importance: {goal.importance}")

            if goal.summary:
                result.append(f"  Summary: {goal.summary}")

            if goal.description:
                desc_lines = goal.description.split("\n")
                result.append(f"  Description: {desc_lines[0]}")
                if len(desc_lines) > 1:
                    result.append(f"    ({len(desc_lines) - 1} more lines)")

            if include_subgoals and goal.subgoals:
                result.append(f"  Subgoals ({len(goal.subgoals)}):")
                for i, subgoal in enumerate(goal.subgoals, 1):
                    result.append(
                        f"    {visible_count}.{i}. {subgoal.title} [{subgoal.status.value}]"
                    )

            result.append("")

        return "\n".join(result)

    def finish_goal(
        self,
        run_context: RunContext,
        goal_id: str | None = None,
        summary: str | None = None,
    ) -> str:
        """Finish a goal and mark it as completed."""
        goals, current_goal_id = _ensure_session_state(run_context)
        assert run_context.session_state is not None
        target_goal_id = goal_id or current_goal_id

        if not target_goal_id or target_goal_id not in goals:
            return "No valid goal to finish. Use list_goals to see available goals."

        goal = goals[target_goal_id]
        goal.status = GoalStatus.COMPLETED
        goal.updated_at = datetime.now().isoformat()

        if summary:
            goal.summary = summary

        next_goal_id = self._find_next_goal(goals)
        if next_goal_id:
            run_context.session_state["current_goal_id"] = next_goal_id
            goals[next_goal_id].status = GoalStatus.IN_PROGRESS
            return (
                f"Completed goal: {goal.title}\n"
                f"  Summary: {summary or goal.summary or 'No summary provided'}\n"
                f"\n"
                f"Next goal: {goals[next_goal_id].title}"
            )
        else:
            run_context.session_state["current_goal_id"] = None
            return (
                f"Completed goal: {goal.title}\n"
                f"  Summary: {summary or goal.summary or 'No summary provided'}\n"
                f"\n"
                f"All goals completed."
            )

    def skip_goal(
        self,
        run_context: RunContext,
        goal_id: str | None = None,
        reason: str | None = None,
    ) -> str:
        """Skip a goal without marking it as finished."""
        goals, current_goal_id = _ensure_session_state(run_context)
        assert run_context.session_state is not None
        target_goal_id = goal_id or current_goal_id

        if not target_goal_id or target_goal_id not in goals:
            return "No valid goal to skip. Use list_goals to see available goals."

        goal = goals[target_goal_id]
        goal.status = GoalStatus.SKIPPED
        goal.updated_at = datetime.now().isoformat()

        next_goal_id = self._find_next_goal(goals)
        if next_goal_id:
            run_context.session_state["current_goal_id"] = next_goal_id
            goals[next_goal_id].status = GoalStatus.IN_PROGRESS
            return (
                f"Skipped goal: {goal.title}\n"
                f"  Reason: {reason or 'Not specified'}\n"
                f"\n"
                f"Next goal: {goals[next_goal_id].title}"
            )
        else:
            run_context.session_state["current_goal_id"] = None
            return (
                f"Skipped goal: {goal.title}\n"
                f"  Reason: {reason or 'Not specified'}\n"
                f"\n"
                f"No more pending goals."
            )

    def refine_goal(
        self,
        run_context: RunContext,
        goal_id: str | None = None,
        new_title: str | None = None,
        new_description: str | None = None,
        new_importance: float | None = None,
        new_priority: str | None = None,
    ) -> str:
        """Refine or update an existing goal's attributes."""
        goals, current_goal_id = _ensure_session_state(run_context)
        target_goal_id = goal_id or current_goal_id

        if not target_goal_id or target_goal_id not in goals:
            return "No valid goal to refine. Use list_goals to see available goals."

        goal = goals[target_goal_id]

        changes: list[str] = []

        if new_title:
            goal.title = new_title
            changes.append(f"title -> {new_title}")

        if new_description:
            goal.description = new_description
            changes.append("description updated")

        if new_importance is not None:
            goal.importance = max(0.0, min(1.0, new_importance))
            changes.append(f"importance -> {goal.importance}")

        if new_priority:
            priority_map = {
                "P0": GoalPriority.HIGHEST,
                "P1": GoalPriority.HIGH,
                "P2": GoalPriority.MEDIUM,
                "P3": GoalPriority.LOW,
            }
            if new_priority in priority_map:
                goal.priority = priority_map[new_priority]
                changes.append(f"priority -> {new_priority}")

        if changes:
            goal.status = GoalStatus.REFINED
            goal.updated_at = datetime.now().isoformat()
            return f"Refined goal '{goal.title}':\n  " + ", ".join(changes)
        else:
            return "No changes specified to refine goal."

    def jump_to_goal(
        self,
        run_context: RunContext,
        goal_id: str,
    ) -> str:
        """Switch to a specific goal and mark it as current goal."""
        goals, _ = _ensure_session_state(run_context)
        assert run_context.session_state is not None

        if goal_id not in goals:
            return f"Goal '{goal_id}' not found. Use list_goals to see available goals."

        goal = goals[goal_id]

        if goal.status == GoalStatus.COMPLETED:
            return f"Goal '{goal.title}' is already completed. Cannot jump to it."

        run_context.session_state["current_goal_id"] = goal_id
        goal.status = GoalStatus.IN_PROGRESS
        goal.updated_at = datetime.now().isoformat()

        return (
            f"Switched to goal: {goal.title}\n"
            f"  Priority: {goal.priority.name} | Importance: {goal.importance}\n"
            f"  Status: {goal.status.value}"
        )

    def set_goal_priority(
        self,
        run_context: RunContext,
        goal_id: str | None = None,
        priority: str = "P2",
    ) -> str:
        """Change the priority of a goal."""
        goals, current_goal_id = _ensure_session_state(run_context)
        target_goal_id = goal_id or current_goal_id

        if not target_goal_id or target_goal_id not in goals:
            return "No valid goal to update. Use list_goals to see available goals."

        goal = goals[target_goal_id]

        priority_map = {
            "P0": GoalPriority.HIGHEST,
            "P1": GoalPriority.HIGH,
            "P2": GoalPriority.MEDIUM,
            "P3": GoalPriority.LOW,
        }
        if priority in priority_map:
            old_priority = goal.priority.name
            goal.priority = priority_map[priority]
            goal.updated_at = datetime.now().isoformat()
            return f"Updated goal '{goal.title}': priority {old_priority} -> {priority}"
        else:
            return f"Invalid priority level '{priority}'. Use P0, P1, P2, or P3."

    def get_current_goal(
        self,
        run_context: RunContext,
    ) -> str:
        """Get the current active goal with full details."""
        goals, current_goal_id = _ensure_session_state(run_context)

        if not current_goal_id or not goals or current_goal_id not in goals:
            return "No active goal set. Use create_goal to create a goal or jump_to_goal to select one."

        goal = goals[current_goal_id]

        result = [
            f"Current goal: {goal.title}",
            f"ID: {goal.id}",
            f"Priority: {goal.priority.name}",
            f"Importance: {goal.importance}",
            f"Status: {goal.status.value}",
        ]

        if goal.summary:
            result.append(f"Summary: {goal.summary}")

        result.append(f"\nDescription:\n{goal.description}")

        if goal.subgoals:
            result.append(f"\nSubgoals ({len(goal.subgoals)}):")
            for i, subgoal in enumerate(goal.subgoals, 1):
                result.append(f"  {i}. {subgoal.title} [{subgoal.status.value}]")

        if goal.parent_goal_id:
            result.append(f"\nParent goal: {goal.parent_goal_id}")

        return "\n".join(result)

    def _find_next_goal(self, goals: GoalsDict, exclude_goal_id: str | None = None) -> str | None:
        """Find the next pending goal by priority, excluding specified goal ID."""
        pending_goals = [
            (gid, g)
            for gid, g in goals.items()
            if g.status in (GoalStatus.PENDING, GoalStatus.IN_PROGRESS) and gid != exclude_goal_id
        ]

        if not pending_goals:
            return None

        priority_order = {
            GoalPriority.HIGHEST: 0,
            GoalPriority.HIGH: 1,
            GoalPriority.MEDIUM: 2,
            GoalPriority.LOW: 3,
        }

        pending_goals.sort(
            key=lambda x: (
                priority_order.get(x[1].priority, 2),
                -(x[1].importance if x[1].importance is not None else 0.5),
            )
        )

        return pending_goals[0][0]
