"""Consensus hooks for Agno agents - Multi-model agreement through structured rounds."""

from blockether_foundation.agents.hooks.consensus.core import (
    ConfidenceBreakdown,
    ConflictResolution,
    ConsensusHooksConfig,
    ConsensusResult,
    ConsensusSynthesis,
    ConsideredAlternative,
    CritiqueFeedback,
    GenerationOutput,
    IncorporatedInsight,
    JudgeCriteria,
    JudgeResult,
    JudgeVerdict,
    ModelConfig,
    ModelContribution,
    RefinementAction,
    RejectedApproach,
    StrengthWeakness,
    SuggestedImprovement,
    TriageDecision,
)
from blockether_foundation.agents.hooks.consensus.presentation import (
    export_consensus_report_to_html,
    generate_consensus_report_html,
)

__all__ = [
    "ConfidenceBreakdown",
    "ConflictResolution",
    "ConsensusHooksConfig",
    "ConsensusResult",
    "ConsensusSynthesis",
    "ConsideredAlternative",
    "CritiqueFeedback",
    "GenerationOutput",
    "IncorporatedInsight",
    "JudgeCriteria",
    "JudgeResult",
    "JudgeVerdict",
    "ModelConfig",
    "ModelContribution",
    "RefinementAction",
    "RejectedApproach",
    "StrengthWeakness",
    "SuggestedImprovement",
    "TriageDecision",
    "export_consensus_report_to_html",
    "generate_consensus_report_html",
]
