"""Consensus HITL Toolkit - Dynamically injected for user feedback."""

from __future__ import annotations

from collections.abc import Awaitable, Callable
from textwrap import dedent
from typing import TYPE_CHECKING, Any

from agno.run import RunContext
from agno.tools import Toolkit
from agno.tools.user_control_flow import UserControlFlowTools
from pydantic import Field

from ....models import BaseModelSerializable, ChainOfThoughts

HITL_STATE_KEY_QUESTIONS = "consensus_hitl_questions"
HITL_STATE_KEY_ANSWERS = "consensus_hitl_answers"
HITL_STATE_KEY_REFINEMENT_RESULT = "consensus_hitl_refinement_result"


class HITLQuestionOption(BaseModelSerializable):
    """An option for a multi-choice question."""

    option_id: str = Field(description="Unique ID like 'a', 'b', 'c'.")
    label: str = Field(description="Short label for this option.")
    description: str | None = Field(
        default=None, description="Detailed explanation of what this option means."
    )


class HITLQuestion(ChainOfThoughts):
    """A multi-choice question for user feedback based on consensus uncertainties.

    Questions should be generated based on areas_of_uncertainty from the synthesis.
    Only generate questions when there are genuine uncertainties that user input can resolve.
    """

    question_id: str = Field(description="Unique identifier for this question.")
    question_text: str = Field(description="The question to ask the user.")
    options: list[HITLQuestionOption] = Field(description="Available answer choices.")
    category: str = Field(
        description="Question type: 'uncertainty', 'preference', 'priority', or 'clarification'."
    )
    allows_multiple: bool = Field(
        default=False, description="Whether multiple options can be selected."
    )
    related_uncertainty: str | None = Field(
        default=None, description="Links to an UncertaintyArea if applicable."
    )


class HITLQuestionnaire(ChainOfThoughts):
    """Questionnaire generated by model from synthesis uncertainties.

    IMPORTANT: Only generate questions when there are genuine uncertainties.
    If the synthesis has high confidence and no significant uncertainties,
    the questions list should be EMPTY - do not fabricate questions.

    Questions should be derived from:
    - areas_of_uncertainty in the synthesis
    - conflict_resolutions where user preference would help
    - low confidence areas that need clarification
    """

    questions: list[HITLQuestion] = Field(
        default=[],
        description="Multi-choice questions for the user. EMPTY if no uncertainties exist.",
    )
    context_summary: str = Field(description="Brief summary of consensus state for user context.")
    synthesis_confidence: float = Field(
        ge=0.0, le=1.0, description="Confidence level of the synthesis."
    )
    should_skip_hitl: bool = Field(
        default=False,
        description="True if HITL should be skipped because there are no meaningful questions to ask.",
    )


# Type alias for the refinement function
RefinementFunc = Callable[..., Awaitable[tuple[str, float, int, list[Any]]]]


class ConsensusHITLToolkit(Toolkit):
    """Toolkit for human-in-the-loop feedback during consensus.

    Dynamically injected by consensus pre-hook when hitl=True.
    Provides tools:
    1. get_user_input() - From UserControlFlowTools, triggers Agno's pause mechanism
    2. run_refinement_with_feedback() - MANDATORY after feedback, runs refinement

    Uses Agno's UserControlFlowTools internally to properly trigger the pause mechanism.
    State is stored in session_state (not in self) to avoid issues with toolkit instances.
    """

    TOOLKIT_NAME = "consensus_hitl"

    def __init__(
        self,
        questionnaire: HITLQuestionnaire,
        synthesis: Any,  # ConsensusSynthesis - avoid import
        refinement_func: RefinementFunc,
        refinement_kwargs: dict[str, Any],
    ):
        self.questionnaire = questionnaire
        self.synthesis = synthesis
        self.refinement_func = refinement_func
        self.refinement_kwargs = refinement_kwargs

        self._user_control_flow = UserControlFlowTools(
            add_instructions=False,
            enable_get_user_input=True,
        )

        all_tools: list[Any] = [self.run_refinement_with_feedback]
        all_tools.extend(self._user_control_flow.tools)

        instructions = self._build_instructions(questionnaire)

        super().__init__(
            name=self.TOOLKIT_NAME,
            tools=all_tools,
            instructions=instructions,
            add_instructions=True,
        )

    @staticmethod
    def _build_user_input_fields(questionnaire: HITLQuestionnaire) -> list[dict[str, str]]:
        if not questionnaire.questions:
            return []

        user_input_fields: list[dict[str, str]] = []
        for q in questionnaire.questions:
            options_display = "\n".join(
                f"  {chr(ord('a') + i)}) {opt.label}"
                + (f" - {opt.description}" if opt.description else "")
                for i, opt in enumerate(q.options)
            )

            user_input_fields.append(
                {
                    "field_name": q.question_id,
                    "field_type": "str",
                    "field_description": f"{q.question_text}\n\nOptions:\n{options_display}\n\n(Enter option letter, e.g., 'a' or 'a,b' for multiple)",
                }
            )

        return user_input_fields

    def _map_letter_to_option_id(self, question_id: str, letter_answer: str) -> str:
        for q in self.questionnaire.questions:
            if q.question_id == question_id:
                letters = [l.strip() for l in letter_answer.split(",")]
                mapped_ids: list[str] = []
                for letter in letters:
                    idx = ord(letter.lower()) - ord("a")
                    if 0 <= idx < len(q.options):
                        mapped_ids.append(q.options[idx].option_id)
                    else:
                        mapped_ids.append(letter)
                return (
                    ",".join(mapped_ids)
                    if len(mapped_ids) > 1
                    else (mapped_ids[0] if mapped_ids else letter_answer)
                )
        return letter_answer

    async def run_refinement_with_feedback(self, run_context: RunContext) -> str:
        """Run refinement with user feedback. Call AFTER get_user_input() and user responds."""
        if run_context.session_state is None:
            return "ERROR: No session state available."

        cached_result = run_context.session_state.get(HITL_STATE_KEY_REFINEMENT_RESULT)
        if cached_result is not None:
            return cached_result

        raw_answers: dict[str, Any] = run_context.session_state.get(HITL_STATE_KEY_ANSWERS, {})
        user_answers: dict[str, str] = {
            qid: self._map_letter_to_option_id(qid, str(ans)) for qid, ans in raw_answers.items()
        }

        # Call the refinement function (passed in to avoid cyclic import)
        (
            refined_output,
            judge_score,
            iterations,
            judge_results,
        ) = await self.refinement_func(**self.refinement_kwargs)

        # Build detailed output including judge results
        judge_details = self._format_judge_results(judge_results)

        result = f"""Refined Consensus Output:

{refined_output}

---
Refinement Summary:
- Synthesis Confidence: {self.synthesis.consensus_confidence:.0%}
- Judge Score: {judge_score:.2f}
- Refinement Iterations: {iterations}
- User Feedback Applied: {len(user_answers)} answers incorporated

{judge_details}"""

        # Cache the result and clean up session state
        run_context.session_state[HITL_STATE_KEY_REFINEMENT_RESULT] = result

        run_context.session_state.pop(HITL_STATE_KEY_QUESTIONS, None)
        run_context.session_state.pop(HITL_STATE_KEY_ANSWERS, None)

        return result

    def _format_judge_results(self, judge_results: list[Any]) -> str:
        """Format judge results for output."""
        if not judge_results:
            return "Judge Details: No judge iterations recorded."

        lines = ["Judge Details:"]
        for jr in judge_results:
            lines.append(f"\n  Iteration {jr.iteration}:")
            lines.append(f"    Overall Score: {jr.overall_score:.2f}")
            lines.append(f"    Passed: {jr.passed}")

            if jr.verdicts:
                lines.append("    Verdicts:")
                for v in jr.verdicts:
                    status = "PASS" if v.passed else "FAIL"
                    lines.append(f"      - {v.criterion_name}: {v.score:.2f} [{status}]")
                    if not v.passed and v.reasoning:
                        lines.append(f"        Reason: {v.reasoning[:100]}...")

            if jr.refinement_actions:
                lines.append("    Refinement Actions:")
                for ra in jr.refinement_actions:
                    action_status = "Fixed" if ra.was_addressed else "Not addressed"
                    lines.append(f"      - {ra.criterion_name}: {action_status}")
                    if ra.reasoning:
                        lines.append(f"        {ra.reasoning[:80]}...")

        return "\n".join(lines)

    @staticmethod
    def _build_instructions(questionnaire: HITLQuestionnaire) -> str:
        import json

        fields_json = ConsensusHITLToolkit._build_user_input_fields(questionnaire)
        if not fields_json:
            return dedent("""\
                Consensus has high confidence with no uncertainties requiring user input.
                Proceed with the synthesized output directly.""")

        fields_str = json.dumps(fields_json, indent=2)
        indented_fields = "\n".join(
            f"    {line}" if line.strip() else "" for line in fields_str.split("\n")
        )
        return dedent(f"""\
            You have access to Consensus HITL Toolkit for gathering user feedback.

            WORKFLOW (MANDATORY):
            1. Call get_user_input with these exact fields:
{indented_fields}

            2. Execution will PAUSE - wait for user to answer
            3. After user responds, you MUST call run_refinement_with_feedback()
            4. Use the refined output in your response

            DO NOT skip run_refinement_with_feedback() after getting feedback!""")
